export const PRODUCTS = [
  {
    productName: "Product 1",
    price: 484.44,
    category: "Food",
    details: {
      description: "This is a sample description for product 1.",
      weight: "",
      dimensions: {
        width: "N/A",
        height: 7,
        depth: 3,
      },
    },
    created_at: 1735162071,
    isAvailable: false,
    status: "available",
    metadata: {
      id: "d4779ca0-8f13-4c25-ab07-9148f9bb8ce3",
      tags: [],
    },
  },
  {
    title: "Product 2",
    cost: null,
    category: "Toys",
    details: {
      description: "This is a sample description for product 2.",
      weight: "",
      dimensions: {
        width: "N/A",
        height: null,
        depth: 2,
      },
    },
    created_at: "2023-06-05",
    isAvailable: "yes",
    status: "available",
    metadata: {
      id: "78aa50ff-37fc-4b7f-965d-d15b5177f2d0",
      tags: ["popular"],
    },
  },
  {
    productName: "Product 3",
    value: "free",
    category: "Tools",
    details: {
      description: "This is a sample description for product 3.",
      weight: "1kg",
      dimensions: {
        width: "N/A",
        height: 5,
        depth: 3,
      },
    },
    created_at: 1699219671,
    isAvailable: "yes",
    status: "available",
    metadata: {
      id: "f2c9a57b-b820-40fa-a7ce-946b7ae4cf73",
      tags: [],
    },
  },
  {
    productName: "Product 4",
    price: "free",
    category: "Toys",
    details: {
      description: "This is a sample description for product 4.",
      weight: "1kg",
      dimensions: {
        width: "N/A",
        height: null,
        depth: 3,
      },
    },
    created_at: 1752787671,
    isAvailable: false,
    status: null,
    metadata: {
      id: "706816e7-40b4-40c1-90ee-04f1c2430112",
      tags: ["eco"],
    },
  },
  {
    productName: "Product 5",
    value: 134.08,
    category: "Tools",
    details: {
      description: "This is a sample description for product 5.",
      weight: "500g",
      dimensions: {
        width: "N/A",
        height: 7,
        depth: 2,
      },
    },
    created_at: 1708464471,
    isAvailable: true,
    status: "",
    metadata: {
      id: "e7a5c779-f30a-4d5a-af02-2c3409724816",
      tags: ["popular", "clearance"],
    },
  },
  {
    title: "Product 6",
    price: null,
    category: "Electronics",
    details: {
      description: "This is a sample description for product 6.",
      weight: "1kg",
      dimensions: {
        width: 10,
        height: 7,
        depth: 2,
      },
    },
    created_at: 1679779671,
    isAvailable: null,
    status: null,
    metadata: {
      id: "397e69cd-0a27-492c-b43a-f594c93ba761",
      tags: [],
    },
  },
  {
    name: "Product 7",
    value: null,
    category: "Toys",
    details: {
      description: "This is a sample description for product 7.",
      weight: null,
      dimensions: {
        width: "N/A",
        height: null,
        depth: 2,
      },
    },
    created_at: "2025-04-24",
    isAvailable: false,
    status: "",
    metadata: {
      id: "aecf899a-4a0d-45b4-bcff-eccbf62cd413",
      tags: [null, "new"],
    },
  },
  {
    title: "Product 8",
    value: 334.23,
    category: "Tools",
    details: {
      description: "This is a sample description for product 8.",
      weight: "500g",
      dimensions: {
        width: null,
        height: null,
        depth: 3,
      },
    },
    created_at: "2025-01-28",
    isAvailable: false,
    status: "",
    metadata: {
      id: "ea0eaf96-05ed-4711-b767-eceb124861d7",
      tags: ["clearance", "sale", "new", null],
    },
  },
  {
    name: "Product 9",
    price: "free",
    category: "Books",
    details: {
      description: "This is a sample description for product 9.",
      weight: "500g",
      dimensions: {
        width: 10,
        height: 5,
        depth: 3,
      },
    },
    created_at: "invalid_date",
    isAvailable: null,
    status: "discontinued",
    metadata: {
      id: "986d8eba-5f18-4ee2-b2fa-25d271ec98bb",
      tags: ["popular", null, "eco"],
    },
  },
  {
    productName: "Product 10",
    price: "free",
    category: "Clothing",
    details: {
      description: "This is a sample description for product 10.",
      weight: "",
      dimensions: {
        width: null,
        height: 5,
        depth: null,
      },
    },
    created_at: "2025-01-21",
    isAvailable: true,
    status: null,
    metadata: {
      id: "1fb8f2e1-6e5b-4922-ae76-8d3d0e9a7f3a",
      tags: [],
    },
  },
  {
    name: "Product 11",
    price: null,
    category: "Clothing",
    details: {
      description: "This is a sample description for product 11.",
      weight: "500g",
      dimensions: {
        width: null,
        height: null,
        depth: 2,
      },
    },
    created_at: 1719955671,
    isAvailable: false,
    status: "discontinued",
    metadata: {
      id: "e03fba5f-4f9c-4041-b4c4-d28e2ef835bf",
      tags: ["popular"],
    },
  },
  {
    productName: "Product 12",
    value: null,
    category: "Tools",
    details: {
      description: "This is a sample description for product 12.",
      weight: "500g",
      dimensions: {
        width: "N/A",
        height: 7,
        depth: 3,
      },
    },
    created_at: "invalid_date",
    isAvailable: true,
    status: "",
    metadata: {
      id: "969408d8-b350-49ce-88c4-7ff871929128",
      tags: [],
    },
  },
  {
    name: "Product 13",
    cost: 300.58,
    category: "Toys",
    details: {
      description: "This is a sample description for product 13.",
      weight: null,
      dimensions: {
        width: "N/A",
        height: null,
        depth: null,
      },
    },
    created_at: 1729632471,
    isAvailable: null,
    status: "available",
    metadata: {
      id: "4c889e6c-d44a-4597-aa8b-1c44e70aec8b",
      tags: ["sale", "new"],
    },
  },
  {
    name: "Product 14",
    cost: null,
    category: "Home",
    details: {
      description: "This is a sample description for product 14.",
      weight: null,
      dimensions: {
        width: null,
        height: 7,
        depth: 2,
      },
    },
    created_at: "2024-06-28",
    isAvailable: true,
    status: "out_of_stock",
    metadata: {
      id: "8bb82697-d522-4f19-974b-114362bee102",
      tags: ["popular"],
    },
  },
  {
    productName: "Product 15",
    cost: "free",
    category: "Toys",
    details: {
      description: "This is a sample description for product 15.",
      weight: "500g",
      dimensions: {
        width: "N/A",
        height: 7,
        depth: 3,
      },
    },
    created_at: 1741123671,
    isAvailable: true,
    status: "discontinued",
    metadata: {
      id: "95a44d1a-c913-4be2-a6e5-4c32fc9765df",
      tags: [],
    },
  },
  {
    title: "Product 16",
    cost: null,
    category: "Garden",
    details: {
      description: "This is a sample description for product 16.",
      weight: "",
      dimensions: {
        width: 10,
        height: null,
        depth: 3,
      },
    },
    created_at: "invalid_date",
    isAvailable: false,
    status: "discontinued",
    metadata: {
      id: "6d73d478-c647-403b-b1fe-dde5dc659d9e",
      tags: [null, "clearance"],
    },
  },
  {
    name: "Product 17",
    cost: 228.06,
    category: "Electronics",
    details: {
      description: "This is a sample description for product 17.",
      weight: "500g",
      dimensions: {
        width: 10,
        height: null,
        depth: 3,
      },
    },
    created_at: "2025-01-04",
    isAvailable: null,
    status: null,
    metadata: {
      id: "f1eb3cbf-7769-4b3b-8b40-352219c2a4e6",
      tags: ["popular", "clearance"],
    },
  },
  {
    name: "Product 18",
    cost: 440.7,
    category: "Home",
    details: {
      description: "This is a sample description for product 18.",
      weight: null,
      dimensions: {
        width: "N/A",
        height: 7,
        depth: 2,
      },
    },
    created_at: 1749504471,
    isAvailable: false,
    status: "out_of_stock",
    metadata: {
      id: "59c1af7a-74a9-4f12-bc08-e2f73949ae92",
      tags: ["sale", null, "clearance", "eco"],
    },
  },
  {
    name: "Product 19",
    value: 338.99,
    category: "Home",
    details: {
      description: "This is a sample description for product 19.",
      weight: "500g",
      dimensions: {
        width: 10,
        height: 5,
        depth: null,
      },
    },
    created_at: "invalid_date",
    isAvailable: true,
    status: "",
    metadata: {
      id: "755af95a-55d0-49b7-9c78-8087c34985e5",
      tags: ["clearance", null],
    },
  },
  {
    title: "Product 20",
    cost: 421.22,
    category: "Tools",
    details: {
      description: "This is a sample description for product 20.",
      weight: "1kg",
      dimensions: {
        width: "N/A",
        height: 7,
        depth: 3,
      },
    },
    created_at: "invalid_date",
    isAvailable: false,
    status: "discontinued",
    metadata: {
      id: "f50b50a2-8e0f-4b68-a44f-490bab7270de",
      tags: [],
    },
  },
  {
    productName: "Product 21",
    cost: null,
    category: "Clothing",
    details: {
      description: "This is a sample description for product 21.",
      weight: "500g",
      dimensions: {
        width: 10,
        height: null,
        depth: 2,
      },
    },
    created_at: 1704230871,
    isAvailable: null,
    status: "out_of_stock",
    metadata: {
      id: "32baacd2-e03e-4b8f-85c2-83626996de3f",
      tags: ["popular"],
    },
  },
  {
    title: "Product 22",
    cost: "free",
    category: "Toys",
    details: {
      description: "This is a sample description for product 22.",
      weight: null,
      dimensions: {
        width: 10,
        height: 7,
        depth: 3,
      },
    },
    created_at: "invalid_date",
    isAvailable: null,
    status: "available",
    metadata: {
      id: "64128eaa-49b6-46ee-a800-609425228777",
      tags: [null, "new", "eco", "clearance"],
    },
  },
  {
    name: "Product 23",
    price: null,
    category: "Toys",
    details: {
      description: "This is a sample description for product 23.",
      weight: "500g",
      dimensions: {
        width: null,
        height: 7,
        depth: 3,
      },
    },
    created_at: "invalid_date",
    isAvailable: null,
    status: "discontinued",
    metadata: {
      id: "2cf6ee3c-781d-42e0-9957-88011f2fda0f",
      tags: ["sale", "new"],
    },
  },
  {
    name: "Product 24",
    value: null,
    category: "Garden",
    details: {
      description: "This is a sample description for product 24.",
      weight: "",
      dimensions: {
        width: "N/A",
        height: 5,
        depth: 3,
      },
    },
    created_at: "invalid_date",
    isAvailable: false,
    status: null,
    metadata: {
      id: "6ef4c502-c54c-442f-bd0d-07b4950a2d15",
      tags: [],
    },
  },
  {
    productName: "Product 25",
    cost: "free",
    category: "Clothing",
    details: {
      description: "This is a sample description for product 25.",
      weight: "500g",
      dimensions: {
        width: "N/A",
        height: null,
        depth: 3,
      },
    },
    created_at: 1752442071,
    isAvailable: "yes",
    status: "available",
    metadata: {
      id: "de05a098-d573-4f5c-b63d-53e4d6abde2d",
      tags: ["clearance"],
    },
  },
  {
    productName: "Product 26",
    value: 251.23,
    category: "Home",
    details: {
      description: "This is a sample description for product 26.",
      weight: "",
      dimensions: {
        width: 10,
        height: 5,
        depth: null,
      },
    },
    created_at: "2024-07-31",
    isAvailable: true,
    status: "discontinued",
    metadata: {
      id: "1ebfaf06-9e2c-4ae3-83e2-eba8582e5239",
      tags: [],
    },
  },
  {
    title: "Product 27",
    value: "free",
    category: "Books",
    details: {
      description: "This is a sample description for product 27.",
      weight: "500g",
      dimensions: {
        width: "N/A",
        height: 5,
        depth: 2,
      },
    },
    created_at: 1675978071,
    isAvailable: "yes",
    status: "available",
    metadata: {
      id: "d88183da-2810-4eef-aeb1-c688422fcabc",
      tags: [null, "clearance", "new"],
    },
  },
  {
    title: "Product 28",
    value: "free",
    category: "Tools",
    details: {
      description: "This is a sample description for product 28.",
      weight: null,
      dimensions: {
        width: "N/A",
        height: 7,
        depth: 2,
      },
    },
    created_at: 1695850071,
    isAvailable: true,
    status: "available",
    metadata: {
      id: "43007b4b-f41a-40d8-998e-69c49da1d8dc",
      tags: ["sale", "clearance", "eco", "new"],
    },
  },
  {
    title: "Product 29",
    value: "free",
    category: "Tools",
    details: {
      description: "This is a sample description for product 29.",
      weight: "500g",
      dimensions: {
        width: 10,
        height: 5,
        depth: 3,
      },
    },
    created_at: "invalid_date",
    isAvailable: true,
    status: "",
    metadata: {
      id: "e5c69ecd-ad86-4ae5-b619-7f456117a737",
      tags: [null, "popular"],
    },
  },
  {
    productName: "Product 30",
    price: "free",
    category: "Clothing",
    details: {
      description: "This is a sample description for product 30.",
      weight: "",
      dimensions: {
        width: null,
        height: null,
        depth: null,
      },
    },
    created_at: 1677014871,
    isAvailable: true,
    status: "out_of_stock",
    metadata: {
      id: "01fd6e0b-19cb-4198-9433-a313f0c65dac",
      tags: ["clearance"],
    },
  },
  {
    name: "Product 31",
    price: 492.29,
    category: "Food",
    details: {
      description: "This is a sample description for product 31.",
      weight: "",
      dimensions: {
        width: null,
        height: 7,
        depth: 2,
      },
    },
    created_at: "invalid_date",
    isAvailable: false,
    status: "out_of_stock",
    metadata: {
      id: "da41c737-374d-4808-92da-003fd9495d5c",
      tags: [null, "clearance", "popular"],
    },
  },
  {
    title: "Product 32",
    value: 205.81,
    category: "Home",
    details: {
      description: "This is a sample description for product 32.",
      weight: "",
      dimensions: {
        width: "N/A",
        height: null,
        depth: 2,
      },
    },
    created_at: "invalid_date",
    isAvailable: false,
    status: "",
    metadata: {
      id: "a04eafe1-20d0-45e1-be44-a7c658627079",
      tags: ["eco"],
    },
  },
  {
    title: "Product 33",
    cost: "free",
    category: "Electronics",
    details: {
      description: "This is a sample description for product 33.",
      weight: null,
      dimensions: {
        width: null,
        height: null,
        depth: 2,
      },
    },
    created_at: 1688160471,
    isAvailable: null,
    status: "",
    metadata: {
      id: "666eacd0-02c1-49e3-9486-eb8766c8e9c9",
      tags: ["clearance", null, "sale"],
    },
  },
  {
    productName: "Product 34",
    cost: null,
    category: "Home",
    details: {
      description: "This is a sample description for product 34.",
      weight: null,
      dimensions: {
        width: null,
        height: 7,
        depth: 3,
      },
    },
    created_at: "invalid_date",
    isAvailable: "yes",
    status: "out_of_stock",
    metadata: {
      id: "f3b4872e-9013-4c85-9cf5-4af093a2767f",
      tags: [null, "sale"],
    },
  },
  {
    title: "Product 35",
    cost: 196.53,
    category: "Clothing",
    details: {
      description: "This is a sample description for product 35.",
      weight: "",
      dimensions: {
        width: 10,
        height: 5,
        depth: null,
      },
    },
    created_at: "invalid_date",
    isAvailable: true,
    status: "discontinued",
    metadata: {
      id: "6f6076d6-839c-427f-997d-1d7ae10d664d",
      tags: [],
    },
  },
  {
    productName: "Product 36",
    cost: 448.89,
    category: "Electronics",
    details: {
      description: "This is a sample description for product 36.",
      weight: null,
      dimensions: {
        width: "N/A",
        height: 7,
        depth: null,
      },
    },
    created_at: "2023-03-13",
    isAvailable: true,
    status: "out_of_stock",
    metadata: {
      id: "45353f4c-2c4b-4a88-bd8f-0b0aec80a6ed",
      tags: ["clearance", "popular", "sale"],
    },
  },
  {
    title: "Product 37",
    value: 210.56,
    category: "Tools",
    details: {
      description: "This is a sample description for product 37.",
      weight: "1kg",
      dimensions: {
        width: null,
        height: null,
        depth: null,
      },
    },
    created_at: "invalid_date",
    isAvailable: false,
    status: "",
    metadata: {
      id: "82213b60-f1e7-4b98-9a96-af4f5be2dc05",
      tags: ["sale", "clearance", "popular"],
    },
  },
  {
    productName: "Product 38",
    cost: 94.15,
    category: "Food",
    details: {
      description: "This is a sample description for product 38.",
      weight: "500g",
      dimensions: {
        width: null,
        height: null,
        depth: 2,
      },
    },
    created_at: 1710106071,
    isAvailable: "yes",
    status: "discontinued",
    metadata: {
      id: "d3f4d3bc-1861-413c-b317-3b465e2695f7",
      tags: [null, "popular"],
    },
  },
  {
    name: "Product 39",
    value: 234.23,
    category: "Home",
    details: {
      description: "This is a sample description for product 39.",
      weight: "",
      dimensions: {
        width: "N/A",
        height: 7,
        depth: null,
      },
    },
    created_at: 1748467671,
    isAvailable: "yes",
    status: "out_of_stock",
    metadata: {
      id: "83e076e8-53cf-4b0d-91cf-32848087c74f",
      tags: ["clearance"],
    },
  },
  {
    title: "Product 40",
    cost: null,
    category: "Tools",
    details: {
      description: "This is a sample description for product 40.",
      weight: "1kg",
      dimensions: {
        width: "N/A",
        height: 5,
        depth: 3,
      },
    },
    created_at: 1682371671,
    isAvailable: true,
    status: "",
    metadata: {
      id: "fe459181-97b9-4b66-8d56-c89e91935446",
      tags: [],
    },
  },
  {
    productName: "Product 41",
    value: "free",
    category: "Garden",
    details: {
      description: "This is a sample description for product 41.",
      weight: "",
      dimensions: {
        width: 10,
        height: null,
        depth: 3,
      },
    },
    created_at: "invalid_date",
    isAvailable: null,
    status: "",
    metadata: {
      id: "731fb4b6-20a4-4b29-9be6-4b5c28454e2d",
      tags: ["clearance", "eco", "sale"],
    },
  },
  {
    title: "Product 42",
    price: null,
    category: "Clothing",
    details: {
      description: "This is a sample description for product 42.",
      weight: null,
      dimensions: {
        width: null,
        height: 5,
        depth: null,
      },
    },
    created_at: "invalid_date",
    isAvailable: true,
    status: "",
    metadata: {
      id: "7ce6c3fa-693c-41fe-957c-25915ce231e5",
      tags: [null, "clearance", "new", "popular"],
    },
  },
  {
    productName: "Product 43",
    cost: 217.91,
    category: "Food",
    details: {
      description: "This is a sample description for product 43.",
      weight: "",
      dimensions: {
        width: "N/A",
        height: 5,
        depth: 3,
      },
    },
    created_at: "2025-07-21",
    isAvailable: "yes",
    status: "out_of_stock",
    metadata: {
      id: "b1b48ff8-04e9-457c-b0f5-7d25ea64d3a0",
      tags: [null, "sale"],
    },
  },
  {
    productName: "Product 44",
    cost: 13.39,
    category: "Tools",
    details: {
      description: "This is a sample description for product 44.",
      weight: null,
      dimensions: {
        width: "N/A",
        height: 7,
        depth: 2,
      },
    },
    created_at: "2023-03-21",
    isAvailable: "yes",
    status: "available",
    metadata: {
      id: "fb2e94c9-0e28-4e81-8292-a07a5c6d304f",
      tags: [],
    },
  },
  {
    title: "Product 45",
    value: "free",
    category: "Clothing",
    details: {
      description: "This is a sample description for product 45.",
      weight: null,
      dimensions: {
        width: 10,
        height: 7,
        depth: 3,
      },
    },
    created_at: "2023-03-19",
    isAvailable: false,
    status: "available",
    metadata: {
      id: "37eaf794-7219-4181-ba64-e6573c5897dc",
      tags: ["clearance", null, "eco", "popular"],
    },
  },
  {
    title: "Product 46",
    price: 205.2,
    category: "Clothing",
    details: {
      description: "This is a sample description for product 46.",
      weight: "500g",
      dimensions: {
        width: "N/A",
        height: 5,
        depth: null,
      },
    },
    created_at: "2023-04-04",
    isAvailable: false,
    status: "",
    metadata: {
      id: "9c7a9647-1d47-422f-b27d-b65dff883d4f",
      tags: [],
    },
  },
  {
    productName: "Product 47",
    cost: 430.62,
    category: "Garden",
    details: {
      description: "This is a sample description for product 47.",
      weight: "500g",
      dimensions: {
        width: "N/A",
        height: null,
        depth: 3,
      },
    },
    created_at: "2024-04-17",
    isAvailable: null,
    status: "available",
    metadata: {
      id: "d755cd83-2c86-4ddd-8963-4145ecd5b677",
      tags: [null],
    },
  },
  {
    productName: "Product 48",
    cost: "free",
    category: "Home",
    details: {
      description: "This is a sample description for product 48.",
      weight: "500g",
      dimensions: {
        width: 10,
        height: 7,
        depth: null,
      },
    },
    created_at: "2024-01-03",
    isAvailable: "yes",
    status: "available",
    metadata: {
      id: "8c68abee-7d22-4384-8e6d-d884120eca95",
      tags: [null],
    },
  },
  {
    title: "Product 49",
    cost: null,
    category: "Toys",
    details: {
      description: "This is a sample description for product 49.",
      weight: null,
      dimensions: {
        width: null,
        height: 7,
        depth: 2,
      },
    },
    created_at: "invalid_date",
    isAvailable: true,
    status: "available",
    metadata: {
      id: "134b15a9-616f-4914-98cc-e12bdda692dd",
      tags: ["eco", "sale", "new", null],
    },
  },
  {
    title: "Product 50",
    price: "free",
    category: "Home",
    details: {
      description: "This is a sample description for product 50.",
      weight: null,
      dimensions: {
        width: null,
        height: 5,
        depth: 3,
      },
    },
    created_at: 1724102871,
    isAvailable: "yes",
    status: "available",
    metadata: {
      id: "05d9004f-bae7-4371-a4e2-f4e267617e94",
      tags: ["popular"],
    },
  },
  {
    name: "Product 51",
    value: null,
    category: "Clothing",
    details: {
      description: "This is a sample description for product 51.",
      weight: null,
      dimensions: {
        width: null,
        height: 5,
        depth: null,
      },
    },
    created_at: "invalid_date",
    isAvailable: true,
    status: "out_of_stock",
    metadata: {
      id: "240fd15c-f193-4e38-bbbc-142391effea3",
      tags: [],
    },
  },
  {
    productName: "Product 52",
    price: 230.24,
    category: "Electronics",
    details: {
      description: "This is a sample description for product 52.",
      weight: "1kg",
      dimensions: {
        width: null,
        height: null,
        depth: null,
      },
    },
    created_at: 1682112471,
    isAvailable: "yes",
    status: "available",
    metadata: {
      id: "77046173-ec2d-4065-9ab0-4df0bf5c6566",
      tags: [],
    },
  },
  {
    productName: "Product 53",
    cost: "free",
    category: "Home",
    details: {
      description: "This is a sample description for product 53.",
      weight: "1kg",
      dimensions: {
        width: "N/A",
        height: 5,
        depth: 3,
      },
    },
    created_at: "2023-02-05",
    isAvailable: true,
    status: "out_of_stock",
    metadata: {
      id: "f37438fa-c701-4076-b806-cab70883d5d0",
      tags: ["clearance", "sale"],
    },
  },
  {
    title: "Product 54",
    price: 146.54,
    category: "Electronics",
    details: {
      description: "This is a sample description for product 54.",
      weight: "",
      dimensions: {
        width: null,
        height: null,
        depth: null,
      },
    },
    created_at: "invalid_date",
    isAvailable: "yes",
    status: "discontinued",
    metadata: {
      id: "9bcc97c3-fe86-4bd8-965e-97cee169a179",
      tags: [null, "clearance", "sale"],
    },
  },
  {
    title: "Product 55",
    price: 268.22,
    category: "Toys",
    details: {
      description: "This is a sample description for product 55.",
      weight: "1kg",
      dimensions: {
        width: null,
        height: 7,
        depth: null,
      },
    },
    created_at: 1675373271,
    isAvailable: true,
    status: "",
    metadata: {
      id: "0e8a6b87-6904-4ed0-a8eb-969043868b22",
      tags: [],
    },
  },
  {
    name: "Product 56",
    cost: "free",
    category: "Toys",
    details: {
      description: "This is a sample description for product 56.",
      weight: "500g",
      dimensions: {
        width: "N/A",
        height: null,
        depth: 2,
      },
    },
    created_at: "invalid_date",
    isAvailable: true,
    status: "available",
    metadata: {
      id: "6ecf19dc-0528-4588-9f53-f394a48ac6cf",
      tags: [null, "popular", "sale"],
    },
  },
  {
    title: "Product 57",
    price: 316.91,
    category: "Home",
    details: {
      description: "This is a sample description for product 57.",
      weight: "500g",
      dimensions: {
        width: null,
        height: 7,
        depth: null,
      },
    },
    created_at: 1669152471,
    isAvailable: "yes",
    status: "",
    metadata: {
      id: "58d92b55-35da-4238-91fc-e1fd76e876dd",
      tags: ["new", null],
    },
  },
  {
    name: "Product 58",
    cost: "free",
    category: "Tools",
    details: {
      description: "This is a sample description for product 58.",
      weight: null,
      dimensions: {
        width: 10,
        height: 5,
        depth: 2,
      },
    },
    created_at: 1738963671,
    isAvailable: "yes",
    status: null,
    metadata: {
      id: "82e0c0bb-5f43-4f56-bdb0-a55201a774bb",
      tags: [],
    },
  },
  {
    name: "Product 59",
    cost: 226.72,
    category: "Toys",
    details: {
      description: "This is a sample description for product 59.",
      weight: "1kg",
      dimensions: {
        width: "N/A",
        height: 7,
        depth: null,
      },
    },
    created_at: 1721683671,
    isAvailable: null,
    status: "available",
    metadata: {
      id: "5298dc2c-d773-44c0-af09-0972beaf2717",
      tags: ["sale"],
    },
  },
  {
    productName: "Product 60",
    price: 258.29,
    category: "Books",
    details: {
      description: "This is a sample description for product 60.",
      weight: "500g",
      dimensions: {
        width: null,
        height: 5,
        depth: 3,
      },
    },
    created_at: 1698960471,
    isAvailable: null,
    status: "available",
    metadata: {
      id: "abaeb86d-38cd-481f-a62f-a5ae6101cec5",
      tags: ["new", "sale"],
    },
  },
  {
    productName: "Product 61",
    value: 417.89,
    category: "Electronics",
    details: {
      description: "This is a sample description for product 61.",
      weight: null,
      dimensions: {
        width: 10,
        height: 7,
        depth: 3,
      },
    },
    created_at: "invalid_date",
    isAvailable: false,
    status: "discontinued",
    metadata: {
      id: "5541f273-94d0-4ace-bc12-8f8f52e6678b",
      tags: ["sale", "popular", "clearance", "eco"],
    },
  },
  {
    title: "Product 62",
    value: 140.56,
    category: "Food",
    details: {
      description: "This is a sample description for product 62.",
      weight: "500g",
      dimensions: {
        width: 10,
        height: null,
        depth: null,
      },
    },
    created_at: 1678570071,
    isAvailable: true,
    status: "out_of_stock",
    metadata: {
      id: "035bee40-5f18-446c-bfc8-81c4d28dd1c5",
      tags: ["clearance"],
    },
  },
  {
    title: "Product 63",
    cost: "free",
    category: "Garden",
    details: {
      description: "This is a sample description for product 63.",
      weight: null,
      dimensions: {
        width: "N/A",
        height: null,
        depth: 3,
      },
    },
    created_at: "invalid_date",
    isAvailable: "yes",
    status: "available",
    metadata: {
      id: "923f0b73-92eb-4d47-819e-1cf16a62480f",
      tags: ["sale", null, "popular", "new"],
    },
  },
  {
    productName: "Product 64",
    value: "free",
    category: "Clothing",
    details: {
      description: "This is a sample description for product 64.",
      weight: "1kg",
      dimensions: {
        width: 10,
        height: null,
        depth: 3,
      },
    },
    created_at: 1703194071,
    isAvailable: true,
    status: "available",
    metadata: {
      id: "e9c5fa48-5db0-46e6-9bd6-c57a77efda31",
      tags: ["eco", "new", "clearance", "sale"],
    },
  },
  {
    name: "Product 65",
    value: null,
    category: "Garden",
    details: {
      description: "This is a sample description for product 65.",
      weight: null,
      dimensions: {
        width: 10,
        height: 5,
        depth: 3,
      },
    },
    created_at: "invalid_date",
    isAvailable: "yes",
    status: "",
    metadata: {
      id: "cd88cbec-3af2-443b-8f3c-6698b3095008",
      tags: [],
    },
  },
  {
    title: "Product 66",
    cost: null,
    category: "Garden",
    details: {
      description: "This is a sample description for product 66.",
      weight: "500g",
      dimensions: {
        width: 10,
        height: 7,
        depth: 2,
      },
    },
    created_at: "invalid_date",
    isAvailable: null,
    status: "",
    metadata: {
      id: "7c4c9555-5cbf-4bc8-82c3-cdb6c579cb19",
      tags: [],
    },
  },
  {
    productName: "Product 67",
    cost: null,
    category: "Home",
    details: {
      description: "This is a sample description for product 67.",
      weight: "500g",
      dimensions: {
        width: 10,
        height: null,
        depth: 3,
      },
    },
    created_at: 1702502871,
    isAvailable: "yes",
    status: "discontinued",
    metadata: {
      id: "89cf9fe6-66e8-49d3-b95b-035967831ed9",
      tags: [null],
    },
  },
  {
    title: "Product 68",
    cost: 155.98,
    category: "Books",
    details: {
      description: "This is a sample description for product 68.",
      weight: null,
      dimensions: {
        width: 10,
        height: 5,
        depth: null,
      },
    },
    created_at: 1694986071,
    isAvailable: null,
    status: "out_of_stock",
    metadata: {
      id: "f5b5a7a1-8725-42d7-be6f-803ba3b8c4c4",
      tags: ["popular", null, "clearance"],
    },
  },
  {
    productName: "Product 69",
    value: null,
    category: "Toys",
    details: {
      description: "This is a sample description for product 69.",
      weight: null,
      dimensions: {
        width: null,
        height: 7,
        depth: 2,
      },
    },
    created_at: 1751405271,
    isAvailable: "yes",
    status: null,
    metadata: {
      id: "0c7ebabd-dca4-4f73-a0bf-c5dec274acec",
      tags: ["sale", "new", "eco", "clearance"],
    },
  },
  {
    productName: "Product 70",
    value: "free",
    category: "Food",
    details: {
      description: "This is a sample description for product 70.",
      weight: "1kg",
      dimensions: {
        width: 10,
        height: 5,
        depth: 2,
      },
    },
    created_at: "invalid_date",
    isAvailable: true,
    status: "",
    metadata: {
      id: "52556736-0677-41d9-b97a-ba201a77973b",
      tags: [null],
    },
  },
  {
    name: "Product 71",
    price: null,
    category: "Home",
    details: {
      description: "This is a sample description for product 71.",
      weight: null,
      dimensions: {
        width: 10,
        height: null,
        depth: null,
      },
    },
    created_at: "invalid_date",
    isAvailable: true,
    status: "out_of_stock",
    metadata: {
      id: "e505c64b-51d7-4bde-99be-e58bfe1acbde",
      tags: ["sale"],
    },
  },
  {
    title: "Product 72",
    cost: 273.04,
    category: "Tools",
    details: {
      description: "This is a sample description for product 72.",
      weight: null,
      dimensions: {
        width: null,
        height: null,
        depth: 3,
      },
    },
    created_at: "2024-03-24",
    isAvailable: false,
    status: "available",
    metadata: {
      id: "d7c4648f-c4e2-4b4d-a088-175dbab51fb0",
      tags: [null, "sale", "new", "eco"],
    },
  },
  {
    title: "Product 73",
    price: null,
    category: "Garden",
    details: {
      description: "This is a sample description for product 73.",
      weight: "",
      dimensions: {
        width: 10,
        height: null,
        depth: null,
      },
    },
    created_at: 1681939671,
    isAvailable: true,
    status: "out_of_stock",
    metadata: {
      id: "ebe25351-8f34-4c18-8404-17c6b50e1dbe",
      tags: [],
    },
  },
  {
    title: "Product 74",
    value: "free",
    category: "Home",
    details: {
      description: "This is a sample description for product 74.",
      weight: "500g",
      dimensions: {
        width: null,
        height: 5,
        depth: null,
      },
    },
    created_at: 1739741271,
    isAvailable: "yes",
    status: "",
    metadata: {
      id: "fb998aeb-04af-4aed-9b47-099670ac4f58",
      tags: [],
    },
  },
  {
    productName: "Product 75",
    price: 186.13,
    category: "Books",
    details: {
      description: "This is a sample description for product 75.",
      weight: null,
      dimensions: {
        width: 10,
        height: null,
        depth: null,
      },
    },
    created_at: 1707254871,
    isAvailable: "yes",
    status: "",
    metadata: {
      id: "1b9bc0dc-8bef-471b-8559-0f935da90daa",
      tags: ["eco", null],
    },
  },
  {
    productName: "Product 76",
    cost: null,
    category: "Garden",
    details: {
      description: "This is a sample description for product 76.",
      weight: "500g",
      dimensions: {
        width: null,
        height: null,
        depth: null,
      },
    },
    created_at: 1704835671,
    isAvailable: true,
    status: "discontinued",
    metadata: {
      id: "b70020f1-cffd-4b32-9243-dc1d1a151555",
      tags: ["new", "clearance"],
    },
  },
  {
    name: "Product 77",
    value: 104.98,
    category: "Tools",
    details: {
      description: "This is a sample description for product 77.",
      weight: "1kg",
      dimensions: {
        width: 10,
        height: null,
        depth: 3,
      },
    },
    created_at: "invalid_date",
    isAvailable: false,
    status: "available",
    metadata: {
      id: "11ecc473-dd70-4268-967a-5118f6419569",
      tags: [],
    },
  },
  {
    productName: "Product 78",
    cost: null,
    category: "Toys",
    details: {
      description: "This is a sample description for product 78.",
      weight: "500g",
      dimensions: {
        width: "N/A",
        height: 7,
        depth: 3,
      },
    },
    created_at: "invalid_date",
    isAvailable: "yes",
    status: "",
    metadata: {
      id: "10979467-3c14-497c-98b1-a68af948739a",
      tags: [],
    },
  },
  {
    name: "Product 79",
    value: null,
    category: "Tools",
    details: {
      description: "This is a sample description for product 79.",
      weight: "500g",
      dimensions: {
        width: null,
        height: null,
        depth: 2,
      },
    },
    created_at: 1740432471,
    isAvailable: false,
    status: "",
    metadata: {
      id: "9af110ec-9362-427c-879e-d5a73f8b9a61",
      tags: ["eco", "clearance", "sale", null],
    },
  },
  {
    title: "Product 80",
    cost: null,
    category: "Electronics",
    details: {
      description: "This is a sample description for product 80.",
      weight: "1kg",
      dimensions: {
        width: null,
        height: 5,
        depth: 2,
      },
    },
    created_at: "2024-08-18",
    isAvailable: true,
    status: "discontinued",
    metadata: {
      id: "bca4f139-6f0d-42c8-8528-85f8742da5da",
      tags: ["new", null, "eco"],
    },
  },
  {
    title: "Product 81",
    value: "free",
    category: "Food",
    details: {
      description: "This is a sample description for product 81.",
      weight: null,
      dimensions: {
        width: null,
        height: null,
        depth: 3,
      },
    },
    created_at: "invalid_date",
    isAvailable: true,
    status: "available",
    metadata: {
      id: "6178d402-00ef-4993-92d9-5da38e09e274",
      tags: ["sale", "eco", "new"],
    },
  },
  {
    title: "Product 82",
    value: "free",
    category: "Garden",
    details: {
      description: "This is a sample description for product 82.",
      weight: "1kg",
      dimensions: {
        width: null,
        height: 7,
        depth: 2,
      },
    },
    created_at: "invalid_date",
    isAvailable: false,
    status: "available",
    metadata: {
      id: "c7a75109-df60-4954-a8f5-95911968bb6b",
      tags: ["sale", "eco", "new"],
    },
  },
  {
    title: "Product 83",
    price: 462.35,
    category: "Books",
    details: {
      description: "This is a sample description for product 83.",
      weight: "500g",
      dimensions: {
        width: 10,
        height: 7,
        depth: 2,
      },
    },
    created_at: 1692480471,
    isAvailable: null,
    status: "available",
    metadata: {
      id: "cb0f2536-45fe-4a47-8480-36c249309f6a",
      tags: ["popular"],
    },
  },
  {
    productName: "Product 84",
    value: null,
    category: "Home",
    details: {
      description: "This is a sample description for product 84.",
      weight: "",
      dimensions: {
        width: "N/A",
        height: 7,
        depth: 3,
      },
    },
    created_at: "2024-08-02",
    isAvailable: false,
    status: "available",
    metadata: {
      id: "05ad3c82-265f-466d-9d0b-82ab01985548",
      tags: [],
    },
  },
  {
    title: "Product 85",
    value: 218.32,
    category: "Garden",
    details: {
      description: "This is a sample description for product 85.",
      weight: "",
      dimensions: {
        width: 10,
        height: null,
        depth: null,
      },
    },
    created_at: 1698528471,
    isAvailable: "yes",
    status: "discontinued",
    metadata: {
      id: "8ee31b76-ccb8-4a3a-a3b8-99616686fec6",
      tags: [],
    },
  },
  {
    title: "Product 86",
    cost: null,
    category: "Garden",
    details: {
      description: "This is a sample description for product 86.",
      weight: "1kg",
      dimensions: {
        width: null,
        height: null,
        depth: 3,
      },
    },
    created_at: "invalid_date",
    isAvailable: true,
    status: "",
    metadata: {
      id: "984f690b-6121-4cbe-bc15-b410b15a2755",
      tags: ["clearance", "eco"],
    },
  },
  {
    name: "Product 87",
    price: 39.15,
    category: "Clothing",
    details: {
      description: "This is a sample description for product 87.",
      weight: "",
      dimensions: {
        width: "N/A",
        height: 5,
        depth: 3,
      },
    },
    created_at: 1726867671,
    isAvailable: "yes",
    status: "",
    metadata: {
      id: "41d4ecfe-3f63-447d-a79b-2ce3f9690e35",
      tags: ["new", "eco", "clearance"],
    },
  },
  {
    title: "Product 88",
    value: 465.94,
    category: "Home",
    details: {
      description: "This is a sample description for product 88.",
      weight: "500g",
      dimensions: {
        width: 10,
        height: 5,
        depth: null,
      },
    },
    created_at: 1727818071,
    isAvailable: null,
    status: "out_of_stock",
    metadata: {
      id: "1c55d9b3-d343-447a-bd2d-ddb003dfc0ec",
      tags: ["new"],
    },
  },
  {
    title: "Product 89",
    cost: "free",
    category: "Electronics",
    details: {
      description: "This is a sample description for product 89.",
      weight: null,
      dimensions: {
        width: "N/A",
        height: 7,
        depth: 3,
      },
    },
    created_at: "invalid_date",
    isAvailable: "yes",
    status: null,
    metadata: {
      id: "fde8e404-a4e6-401d-9635-c551aab7ced7",
      tags: [],
    },
  },
  {
    name: "Product 90",
    value: "free",
    category: "Electronics",
    details: {
      description: "This is a sample description for product 90.",
      weight: "1kg",
      dimensions: {
        width: 10,
        height: null,
        depth: 3,
      },
    },
    created_at: "invalid_date",
    isAvailable: "yes",
    status: "out_of_stock",
    metadata: {
      id: "af648e06-09cb-4695-8405-e40dd80edf9b",
      tags: [null, "sale"],
    },
  },
  {
    productName: "Product 91",
    cost: null,
    category: "Toys",
    details: {
      description: "This is a sample description for product 91.",
      weight: "500g",
      dimensions: {
        width: null,
        height: 7,
        depth: null,
      },
    },
    created_at: "invalid_date",
    isAvailable: true,
    status: null,
    metadata: {
      id: "7d96ad60-823c-47db-8c17-fa5512227af6",
      tags: ["clearance", "new"],
    },
  },
  {
    title: "Product 92",
    cost: 404.18,
    category: "Toys",
    details: {
      description: "This is a sample description for product 92.",
      weight: "500g",
      dimensions: {
        width: "N/A",
        height: 5,
        depth: 3,
      },
    },
    created_at: 1730064471,
    isAvailable: true,
    status: null,
    metadata: {
      id: "c0a913cb-acc7-450d-b387-473a27e14676",
      tags: ["eco", "new", "sale", "popular"],
    },
  },
  {
    title: "Product 93",
    value: null,
    category: "Books",
    details: {
      description: "This is a sample description for product 93.",
      weight: "",
      dimensions: {
        width: "N/A",
        height: 7,
        depth: null,
      },
    },
    created_at: "2024-07-02",
    isAvailable: true,
    status: "available",
    metadata: {
      id: "d54785c6-e9d7-43f3-b76c-f14d2cafb64b",
      tags: ["sale", "new", "eco"],
    },
  },
  {
    productName: "Product 94",
    cost: 71.82,
    category: "Clothing",
    details: {
      description: "This is a sample description for product 94.",
      weight: null,
      dimensions: {
        width: null,
        height: 5,
        depth: 2,
      },
    },
    created_at: "2025-06-25",
    isAvailable: "yes",
    status: null,
    metadata: {
      id: "339c2756-71de-4f8d-9674-562b4a7fca61",
      tags: ["sale", "new"],
    },
  },
  {
    title: "Product 95",
    price: "free",
    category: "Food",
    details: {
      description: "This is a sample description for product 95.",
      weight: null,
      dimensions: {
        width: 10,
        height: 5,
        depth: null,
      },
    },
    created_at: "2024-09-23",
    isAvailable: "yes",
    status: "",
    metadata: {
      id: "d0ad9ff6-dc7a-442b-8ffc-aa99b6dd1c18",
      tags: [],
    },
  },
  {
    name: "Product 96",
    price: "free",
    category: "Electronics",
    details: {
      description: "This is a sample description for product 96.",
      weight: "1kg",
      dimensions: {
        width: 10,
        height: 5,
        depth: 2,
      },
    },
    created_at: "invalid_date",
    isAvailable: false,
    status: "discontinued",
    metadata: {
      id: "3282014c-353e-4fd2-ad2e-9677ede53213",
      tags: ["sale"],
    },
  },
  {
    productName: "Product 97",
    cost: 409.07,
    category: "Clothing",
    details: {
      description: "This is a sample description for product 97.",
      weight: "500g",
      dimensions: {
        width: 10,
        height: null,
        depth: 2,
      },
    },
    created_at: "2023-01-23",
    isAvailable: true,
    status: "out_of_stock",
    metadata: {
      id: "2d69825b-e1fd-4c8b-ad33-450860eabac8",
      tags: ["sale", "clearance", "new", "eco"],
    },
  },
  {
    productName: "Product 98",
    price: null,
    category: "Tools",
    details: {
      description: "This is a sample description for product 98.",
      weight: "1kg",
      dimensions: {
        width: "N/A",
        height: 7,
        depth: 2,
      },
    },
    created_at: "invalid_date",
    isAvailable: null,
    status: "out_of_stock",
    metadata: {
      id: "ad554e49-3f23-4802-a4a2-15ab5694f2c6",
      tags: [null],
    },
  },
  {
    title: "Product 99",
    price: "free",
    category: "Electronics",
    details: {
      description: "This is a sample description for product 99.",
      weight: "500g",
      dimensions: {
        width: "N/A",
        height: 5,
        depth: 3,
      },
    },
    created_at: 1751750871,
    isAvailable: null,
    status: "",
    metadata: {
      id: "3a2d7f19-6be1-4fc4-b1f2-aee878317834",
      tags: ["eco"],
    },
  },
  {
    productName: "Product 100",
    cost: "free",
    category: "Toys",
    details: {
      description: "This is a sample description for product 100.",
      weight: "1kg",
      dimensions: {
        width: 10,
        height: null,
        depth: 2,
      },
    },
    created_at: "invalid_date",
    isAvailable: true,
    status: "available",
    metadata: {
      id: "e4875f9d-1302-4602-9430-fee1bed3a36f",
      tags: ["sale", "popular", "new", null],
    },
  },
  {
    productName: "Product 101",
    cost: "free",
    category: "Food",
    details: {
      description: "This is a sample description for product 101.",
      weight: null,
      dimensions: {
        width: null,
        height: 5,
        depth: 3,
      },
    },
    created_at: "2023-01-26",
    isAvailable: "yes",
    status: "discontinued",
    metadata: {
      id: "343adcad-0575-4f8c-81aa-a762e178bd4a",
      tags: ["clearance"],
    },
  },
  {
    title: "Product 102",
    cost: null,
    category: "Food",
    details: {
      description: "This is a sample description for product 102.",
      weight: "500g",
      dimensions: {
        width: "N/A",
        height: 7,
        depth: 2,
      },
    },
    created_at: "2025-05-26",
    isAvailable: false,
    status: null,
    metadata: {
      id: "ffbbbd1a-4e07-4002-96a9-5565c0e3aea9",
      tags: [],
    },
  },
  {
    name: "Product 103",
    cost: null,
    category: "Garden",
    details: {
      description: "This is a sample description for product 103.",
      weight: "500g",
      dimensions: {
        width: 10,
        height: null,
        depth: 2,
      },
    },
    created_at: "2024-02-26",
    isAvailable: false,
    status: "out_of_stock",
    metadata: {
      id: "c4525a2d-fc5f-42b6-8f61-53b4157b9a16",
      tags: ["new"],
    },
  },
  {
    title: "Product 104",
    cost: 263.13,
    category: "Clothing",
    details: {
      description: "This is a sample description for product 104.",
      weight: null,
      dimensions: {
        width: "N/A",
        height: 7,
        depth: null,
      },
    },
    created_at: "2023-11-15",
    isAvailable: "yes",
    status: "",
    metadata: {
      id: "682298e4-4246-4490-88dc-964a6710beb8",
      tags: ["eco", null],
    },
  },
  {
    title: "Product 105",
    cost: "free",
    category: "Books",
    details: {
      description: "This is a sample description for product 105.",
      weight: "",
      dimensions: {
        width: null,
        height: 7,
        depth: 2,
      },
    },
    created_at: "2024-04-17",
    isAvailable: false,
    status: "discontinued",
    metadata: {
      id: "2ca94f47-0b23-4efc-8527-6a7a11c34698",
      tags: [],
    },
  },
  {
    title: "Product 106",
    cost: 355.4,
    category: "Clothing",
    details: {
      description: "This is a sample description for product 106.",
      weight: "1kg",
      dimensions: {
        width: null,
        height: 5,
        depth: 3,
      },
    },
    created_at: "invalid_date",
    isAvailable: "yes",
    status: "",
    metadata: {
      id: "2facd39b-1e9e-4a60-8150-2575aa9dac63",
      tags: ["clearance", "new"],
    },
  },
  {
    title: "Product 107",
    value: "free",
    category: "Toys",
    details: {
      description: "This is a sample description for product 107.",
      weight: "1kg",
      dimensions: {
        width: 10,
        height: null,
        depth: null,
      },
    },
    created_at: "2023-10-31",
    isAvailable: "yes",
    status: "",
    metadata: {
      id: "b997aa07-8f87-48f6-987e-2bd56d969b28",
      tags: ["new", "clearance"],
    },
  },
  {
    title: "Product 108",
    price: "free",
    category: "Clothing",
    details: {
      description: "This is a sample description for product 108.",
      weight: "1kg",
      dimensions: {
        width: "N/A",
        height: 7,
        depth: 3,
      },
    },
    created_at: "2024-11-05",
    isAvailable: "yes",
    status: "",
    metadata: {
      id: "c568dbde-0798-4561-b307-adc10d852771",
      tags: ["popular"],
    },
  },
  {
    name: "Product 109",
    price: 200.95,
    category: "Garden",
    details: {
      description: "This is a sample description for product 109.",
      weight: "1kg",
      dimensions: {
        width: 10,
        height: null,
        depth: 3,
      },
    },
    created_at: "2024-09-24",
    isAvailable: false,
    status: "",
    metadata: {
      id: "89b32493-46a3-46ba-b91c-362923e65c90",
      tags: ["new", "sale", "clearance", "eco"],
    },
  },
  {
    name: "Product 110",
    cost: 46.34,
    category: "Home",
    details: {
      description: "This is a sample description for product 110.",
      weight: null,
      dimensions: {
        width: null,
        height: null,
        depth: null,
      },
    },
    created_at: "2025-06-11",
    isAvailable: true,
    status: "out_of_stock",
    metadata: {
      id: "3debe078-ff4c-4e23-b93e-3b5ad313e164",
      tags: ["sale", null],
    },
  },
  {
    title: "Product 111",
    cost: "free",
    category: "Food",
    details: {
      description: "This is a sample description for product 111.",
      weight: null,
      dimensions: {
        width: 10,
        height: 7,
        depth: 2,
      },
    },
    created_at: "2025-02-07",
    isAvailable: "yes",
    status: "available",
    metadata: {
      id: "e34629a6-343a-4af4-9ba5-893153c6e5d0",
      tags: [null, "new", "eco", "sale"],
    },
  },
  {
    name: "Product 112",
    value: "free",
    category: "Books",
    details: {
      description: "This is a sample description for product 112.",
      weight: null,
      dimensions: {
        width: 10,
        height: null,
        depth: null,
      },
    },
    created_at: "2023-11-20",
    isAvailable: null,
    status: "",
    metadata: {
      id: "7d58aff0-2488-4dfc-827b-5c422a0a144e",
      tags: ["clearance"],
    },
  },
  {
    title: "Product 113",
    price: null,
    category: "Food",
    details: {
      description: "This is a sample description for product 113.",
      weight: "",
      dimensions: {
        width: 10,
        height: 7,
        depth: null,
      },
    },
    created_at: "invalid_date",
    isAvailable: false,
    status: "available",
    metadata: {
      id: "85b9cff2-1060-40aa-961c-abea7867a7f1",
      tags: ["popular"],
    },
  },
  {
    title: "Product 114",
    cost: null,
    category: "Electronics",
    details: {
      description: "This is a sample description for product 114.",
      weight: "",
      dimensions: {
        width: "N/A",
        height: 7,
        depth: 2,
      },
    },
    created_at: "2025-01-10",
    isAvailable: false,
    status: null,
    metadata: {
      id: "466143c1-84e9-40be-8765-6070a14fa4a9",
      tags: [null, "new", "sale", "clearance"],
    },
  },
  {
    title: "Product 115",
    value: 102.97,
    category: "Electronics",
    details: {
      description: "This is a sample description for product 115.",
      weight: "1kg",
      dimensions: {
        width: 10,
        height: null,
        depth: null,
      },
    },
    created_at: "2025-06-16",
    isAvailable: false,
    status: "discontinued",
    metadata: {
      id: "15e75ed0-286c-49f1-83d3-b3654cfbaf5a",
      tags: ["sale"],
    },
  },
  {
    title: "Product 116",
    price: null,
    category: "Tools",
    details: {
      description: "This is a sample description for product 116.",
      weight: "",
      dimensions: {
        width: null,
        height: 7,
        depth: null,
      },
    },
    created_at: "2023-11-24",
    isAvailable: "yes",
    status: null,
    metadata: {
      id: "d7dae57f-7d4e-440e-9438-95aa65900784",
      tags: [null],
    },
  },
  {
    title: "Product 117",
    cost: 382.24,
    category: "Toys",
    details: {
      description: "This is a sample description for product 117.",
      weight: "1kg",
      dimensions: {
        width: null,
        height: 7,
        depth: null,
      },
    },
    created_at: "invalid_date",
    isAvailable: false,
    status: "available",
    metadata: {
      id: "99e9f426-c313-44f6-955a-294f1b33217e",
      tags: ["sale", "eco", null, "popular"],
    },
  },
  {
    productName: "Product 118",
    price: "free",
    category: "Tools",
    details: {
      description: "This is a sample description for product 118.",
      weight: "",
      dimensions: {
        width: null,
        height: null,
        depth: 3,
      },
    },
    created_at: 1726694871,
    isAvailable: "yes",
    status: "discontinued",
    metadata: {
      id: "ef1fe438-8cd3-4878-9401-a87acdd4ee55",
      tags: [null, "eco"],
    },
  },
  {
    productName: "Product 119",
    price: null,
    category: "Garden",
    details: {
      description: "This is a sample description for product 119.",
      weight: "",
      dimensions: {
        width: 10,
        height: null,
        depth: 3,
      },
    },
    created_at: "2023-05-08",
    isAvailable: false,
    status: "discontinued",
    metadata: {
      id: "d97accec-1338-4e3e-ab2d-bef83d919542",
      tags: ["clearance", null, "eco", "new"],
    },
  },
  {
    name: "Product 120",
    price: "free",
    category: "Electronics",
    details: {
      description: "This is a sample description for product 120.",
      weight: null,
      dimensions: {
        width: null,
        height: 7,
        depth: 2,
      },
    },
    created_at: "invalid_date",
    isAvailable: null,
    status: "out_of_stock",
    metadata: {
      id: "d12ef5de-1f98-499e-9ff3-325eefa51e8c",
      tags: ["eco", "popular", null],
    },
  },
  {
    name: "Product 121",
    cost: 216.2,
    category: "Garden",
    details: {
      description: "This is a sample description for product 121.",
      weight: null,
      dimensions: {
        width: "N/A",
        height: 5,
        depth: 2,
      },
    },
    created_at: 1689542871,
    isAvailable: "yes",
    status: "discontinued",
    metadata: {
      id: "584452c6-3981-48a4-8a3f-2a57f19f18e2",
      tags: ["sale"],
    },
  },
  {
    title: "Product 122",
    value: 441.16,
    category: "Books",
    details: {
      description: "This is a sample description for product 122.",
      weight: "",
      dimensions: {
        width: "N/A",
        height: null,
        depth: 3,
      },
    },
    created_at: "invalid_date",
    isAvailable: false,
    status: "",
    metadata: {
      id: "4c5462ad-1e82-4c82-b488-5d51326cc790",
      tags: ["popular", "new", "eco"],
    },
  },
  {
    title: "Product 123",
    price: 137.94,
    category: "Electronics",
    details: {
      description: "This is a sample description for product 123.",
      weight: "500g",
      dimensions: {
        width: null,
        height: 5,
        depth: null,
      },
    },
    created_at: "invalid_date",
    isAvailable: true,
    status: "",
    metadata: {
      id: "c25a5017-890f-47c8-b39b-af325f68e342",
      tags: ["eco", "sale", "new"],
    },
  },
  {
    productName: "Product 124",
    cost: 11.6,
    category: "Electronics",
    details: {
      description: "This is a sample description for product 124.",
      weight: null,
      dimensions: {
        width: null,
        height: null,
        depth: null,
      },
    },
    created_at: 1710624471,
    isAvailable: null,
    status: "available",
    metadata: {
      id: "a73d9249-4446-4348-b72c-e3927b9cbd9e",
      tags: [null, "eco"],
    },
  },
  {
    name: "Product 125",
    cost: 120.03,
    category: "Toys",
    details: {
      description: "This is a sample description for product 125.",
      weight: null,
      dimensions: {
        width: null,
        height: null,
        depth: 3,
      },
    },
    created_at: "2024-02-22",
    isAvailable: null,
    status: "available",
    metadata: {
      id: "e77e1d85-0342-4f14-83bd-bb361f42a612",
      tags: ["popular", "sale", null, "clearance"],
    },
  },
  {
    name: "Product 126",
    price: "free",
    category: "Clothing",
    details: {
      description: "This is a sample description for product 126.",
      weight: null,
      dimensions: {
        width: "N/A",
        height: 5,
        depth: 3,
      },
    },
    created_at: "invalid_date",
    isAvailable: false,
    status: "",
    metadata: {
      id: "fa4d4c97-9389-4e49-a884-332250524f2d",
      tags: ["popular", "new", "sale", null],
    },
  },
  {
    productName: "Product 127",
    price: null,
    category: "Tools",
    details: {
      description: "This is a sample description for product 127.",
      weight: "1kg",
      dimensions: {
        width: null,
        height: 5,
        depth: 2,
      },
    },
    created_at: "2024-07-13",
    isAvailable: "yes",
    status: "available",
    metadata: {
      id: "cbbeb492-e436-44e1-be36-194a4b4f0bd5",
      tags: [],
    },
  },
  {
    title: "Product 128",
    cost: "free",
    category: "Electronics",
    details: {
      description: "This is a sample description for product 128.",
      weight: "500g",
      dimensions: {
        width: null,
        height: null,
        depth: 3,
      },
    },
    created_at: "2023-04-15",
    isAvailable: "yes",
    status: "",
    metadata: {
      id: "12ea8dae-c5d8-41dc-bf01-53e7a937800f",
      tags: ["clearance", "sale", "popular"],
    },
  },
  {
    name: "Product 129",
    value: 126.88,
    category: "Home",
    details: {
      description: "This is a sample description for product 129.",
      weight: "",
      dimensions: {
        width: 10,
        height: 7,
        depth: 3,
      },
    },
    created_at: 1737235671,
    isAvailable: true,
    status: "",
    metadata: {
      id: "52c71ef8-6700-404e-88b5-03ff8d0c215c",
      tags: ["sale", "clearance", null],
    },
  },
  {
    name: "Product 130",
    cost: "free",
    category: "Food",
    details: {
      description: "This is a sample description for product 130.",
      weight: "1kg",
      dimensions: {
        width: null,
        height: null,
        depth: 3,
      },
    },
    created_at: "2024-06-04",
    isAvailable: false,
    status: "discontinued",
    metadata: {
      id: "8cd2127c-42dd-4aa4-a530-bd76442a988b",
      tags: [],
    },
  },
  {
    name: "Product 131",
    value: null,
    category: "Home",
    details: {
      description: "This is a sample description for product 131.",
      weight: "",
      dimensions: {
        width: "N/A",
        height: null,
        depth: 3,
      },
    },
    created_at: "invalid_date",
    isAvailable: true,
    status: "out_of_stock",
    metadata: {
      id: "792c24ce-e0e7-41c2-950c-fb9c891491aa",
      tags: ["popular", "new"],
    },
  },
  {
    title: "Product 132",
    price: 135.41,
    category: "Tools",
    details: {
      description: "This is a sample description for product 132.",
      weight: "",
      dimensions: {
        width: null,
        height: null,
        depth: 3,
      },
    },
    created_at: "invalid_date",
    isAvailable: null,
    status: "available",
    metadata: {
      id: "e64a3888-028a-46fc-81d7-29e7680f5c35",
      tags: ["eco", "popular", "new", "clearance"],
    },
  },
  {
    name: "Product 133",
    price: null,
    category: "Clothing",
    details: {
      description: "This is a sample description for product 133.",
      weight: "1kg",
      dimensions: {
        width: null,
        height: 7,
        depth: 3,
      },
    },
    created_at: 1675114071,
    isAvailable: false,
    status: null,
    metadata: {
      id: "b94e3a31-174a-4b0e-b29d-026a75754920",
      tags: [],
    },
  },
  {
    title: "Product 134",
    cost: null,
    category: "Clothing",
    details: {
      description: "This is a sample description for product 134.",
      weight: "500g",
      dimensions: {
        width: 10,
        height: 7,
        depth: 3,
      },
    },
    created_at: "invalid_date",
    isAvailable: "yes",
    status: "available",
    metadata: {
      id: "619d9c09-6fa3-4d47-b113-e7cff1870efb",
      tags: [null],
    },
  },
  {
    name: "Product 135",
    price: 427.03,
    category: "Toys",
    details: {
      description: "This is a sample description for product 135.",
      weight: null,
      dimensions: {
        width: 10,
        height: 5,
        depth: 3,
      },
    },
    created_at: "invalid_date",
    isAvailable: false,
    status: "",
    metadata: {
      id: "a8591b96-800a-4ead-9c73-ca05c8cf7215",
      tags: ["new"],
    },
  },
  {
    title: "Product 136",
    value: null,
    category: "Clothing",
    details: {
      description: "This is a sample description for product 136.",
      weight: "500g",
      dimensions: {
        width: null,
        height: 7,
        depth: 2,
      },
    },
    created_at: 1688678871,
    isAvailable: false,
    status: "out_of_stock",
    metadata: {
      id: "0aac1324-b62e-4f46-b380-efae6cda9cb7",
      tags: ["clearance", "sale", "new"],
    },
  },
  {
    productName: "Product 137",
    value: 285.34,
    category: "Food",
    details: {
      description: "This is a sample description for product 137.",
      weight: "500g",
      dimensions: {
        width: 10,
        height: 5,
        depth: 2,
      },
    },
    created_at: "2022-12-04",
    isAvailable: true,
    status: "available",
    metadata: {
      id: "a63d181c-4dee-4ea0-8fe5-3060c6e3e177",
      tags: ["eco", "clearance", "new", "sale"],
    },
  },
  {
    title: "Product 138",
    cost: null,
    category: "Home",
    details: {
      description: "This is a sample description for product 138.",
      weight: "",
      dimensions: {
        width: "N/A",
        height: 5,
        depth: 3,
      },
    },
    created_at: "invalid_date",
    isAvailable: false,
    status: null,
    metadata: {
      id: "89128b4c-638d-42db-b8ce-45d5f0cd2183",
      tags: ["popular", "eco", null, "sale"],
    },
  },
  {
    title: "Product 139",
    price: 12.29,
    category: "Books",
    details: {
      description: "This is a sample description for product 139.",
      weight: "1kg",
      dimensions: {
        width: null,
        height: 7,
        depth: 3,
      },
    },
    created_at: "invalid_date",
    isAvailable: false,
    status: "available",
    metadata: {
      id: "aaded914-b0b9-4359-9ef1-092a52d2f99c",
      tags: ["clearance", "eco", "new", "popular"],
    },
  },
  {
    title: "Product 140",
    cost: null,
    category: "Home",
    details: {
      description: "This is a sample description for product 140.",
      weight: "",
      dimensions: {
        width: null,
        height: 5,
        depth: null,
      },
    },
    created_at: "invalid_date",
    isAvailable: null,
    status: "discontinued",
    metadata: {
      id: "f2c04b1e-6e08-4590-984b-23f06643e1bd",
      tags: ["popular", "eco", null],
    },
  },
  {
    title: "Product 141",
    cost: null,
    category: "Home",
    details: {
      description: "This is a sample description for product 141.",
      weight: "1kg",
      dimensions: {
        width: null,
        height: null,
        depth: 2,
      },
    },
    created_at: "invalid_date",
    isAvailable: false,
    status: "available",
    metadata: {
      id: "0a8be86b-6910-461b-8c9a-0d838ee54ebd",
      tags: ["popular"],
    },
  },
  {
    name: "Product 142",
    price: null,
    category: "Home",
    details: {
      description: "This is a sample description for product 142.",
      weight: null,
      dimensions: {
        width: null,
        height: null,
        depth: null,
      },
    },
    created_at: "2024-05-20",
    isAvailable: "yes",
    status: "discontinued",
    metadata: {
      id: "8080322d-bcf6-404e-bbdd-e3369041b27a",
      tags: ["sale", "clearance"],
    },
  },
  {
    name: "Product 143",
    value: "free",
    category: "Food",
    details: {
      description: "This is a sample description for product 143.",
      weight: "1kg",
      dimensions: {
        width: 10,
        height: null,
        depth: 3,
      },
    },
    created_at: 1729200471,
    isAvailable: null,
    status: "available",
    metadata: {
      id: "cb430c42-c3ab-46f3-8ea6-65342ee579d9",
      tags: ["new", "sale", "clearance"],
    },
  },
  {
    title: "Product 144",
    price: "free",
    category: "Books",
    details: {
      description: "This is a sample description for product 144.",
      weight: "1kg",
      dimensions: {
        width: "N/A",
        height: null,
        depth: 3,
      },
    },
    created_at: 1753651671,
    isAvailable: true,
    status: null,
    metadata: {
      id: "635d91e2-0ca6-459f-9db1-732f02b9c7fe",
      tags: ["sale", "eco"],
    },
  },
  {
    name: "Product 145",
    price: null,
    category: "Clothing",
    details: {
      description: "This is a sample description for product 145.",
      weight: "1kg",
      dimensions: {
        width: null,
        height: 5,
        depth: 3,
      },
    },
    created_at: "2023-05-12",
    isAvailable: "yes",
    status: "discontinued",
    metadata: {
      id: "901181f4-057b-4f8c-adb0-8f7b329006a9",
      tags: [null],
    },
  },
  {
    title: "Product 146",
    price: null,
    category: "Home",
    details: {
      description: "This is a sample description for product 146.",
      weight: "500g",
      dimensions: {
        width: "N/A",
        height: 5,
        depth: null,
      },
    },
    created_at: 1668288471,
    isAvailable: null,
    status: "",
    metadata: {
      id: "f0321e33-de28-41f4-ab12-083bb63e89ec",
      tags: ["sale"],
    },
  },
  {
    productName: "Product 147",
    value: "free",
    category: "Food",
    details: {
      description: "This is a sample description for product 147.",
      weight: "1kg",
      dimensions: {
        width: 10,
        height: 5,
        depth: null,
      },
    },
    created_at: "2025-03-10",
    isAvailable: true,
    status: "out_of_stock",
    metadata: {
      id: "a8695635-03f1-4559-a8f3-39dbdffd2f5a",
      tags: ["new", null],
    },
  },
  {
    title: "Product 148",
    cost: null,
    category: "Electronics",
    details: {
      description: "This is a sample description for product 148.",
      weight: "1kg",
      dimensions: {
        width: 10,
        height: 5,
        depth: 2,
      },
    },
    created_at: "invalid_date",
    isAvailable: false,
    status: "",
    metadata: {
      id: "350d98e4-6ee1-4330-a3e4-5061a999e7a7",
      tags: ["eco", "sale", "new", "popular"],
    },
  },
  {
    productName: "Product 149",
    cost: "free",
    category: "Food",
    details: {
      description: "This is a sample description for product 149.",
      weight: null,
      dimensions: {
        width: null,
        height: 5,
        depth: null,
      },
    },
    created_at: 1673904471,
    isAvailable: null,
    status: null,
    metadata: {
      id: "692a306b-00f6-4299-ad1b-8f65c96f5a97",
      tags: ["clearance", "new"],
    },
  },
  {
    title: "Product 150",
    price: null,
    category: "Toys",
    details: {
      description: "This is a sample description for product 150.",
      weight: "1kg",
      dimensions: {
        width: "N/A",
        height: 7,
        depth: 3,
      },
    },
    created_at: "2025-03-08",
    isAvailable: false,
    status: "discontinued",
    metadata: {
      id: "d24e5c32-4b33-4e39-88c3-3a025d94f7f4",
      tags: ["clearance", "sale", null, "popular"],
    },
  },
];
